version: '3'

services:
  api-backend:
    command: yarn dev
    build:
      context: .
      args:
        - NODE_ENV=development
    volumes:
      - ./:/home/node/app/
      - /home/node/app/node_modules/
    ports:
      - '3000:3000'
